#########################
## OAuth Service       ##
#########################
# Google OAuth Proxy
#authproxy:
#  build: ./oauth
#  command: --cookie-secure=false --upstream="http://nginx:80" --http-address="0.0.0.0:4180" --redirect-url="http://idea.kippchicago.org/oauth2/callback" --email-domain="kippchicago.org"
#  links:
#    - nginx
#  ports:
#    - "80:4180"
#  env_file:
#    - ./oauth/.env

version: '2'
services:
#########################
##  Cron / ETL Service ##
#########################

  cron:
    build: ./cron/
    expose:
      - "8787"
    ports:
      - "8787:8787"
    volumes:
      - ./cron/jobs:/jobs
      #- /data
    volumes_from:
      - data
      - shiny



  #########################
  ##  Data Volume        ##
  #########################
  data:
      build: ./data/
      #volumes_from:
      #  - cron
      volumes:
       - /data
       - ./data/config:/config

  ####################################
  ## Postrgres for Airflow service  ##
  ####################################
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  #########################
  ## Airflow service     ##
  #########################
  airflow:
    build: ./airflow
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
    command: webserver


  #########################
  ## Shiny Service       ##
  #########################
  shiny:
    build: ./shiny/
    expose:
      - "3838"
    ports:
      - "3838:3838"
    volumes_from:
      - data
    volumes:
      - ./shiny/war/:/srv/shiny-server/war
      - ./shiny/map/:/srv/shiny-server/map
      - ./shiny/recruit/:/srv/shiny-server/recruit
      - ./shiny/assignments/:/srv/shiny-server/assignments
      - ./shiny/ktc/:/srv/shiny-server/ktc
