#########################
##  Data Volume        ##
#########################
data:
    build: ./data/
    #volumes_from:
    #  - cron
    volumes:
     - /data
     - ./configs:/configs


#########################
##  Cron / ETL Service ##
#########################
cron:
    build: ./cron/
    volumes:
     - ./cron/jobs:/jobs
     - /data
    volumes_from:
      - data
      - shiny
    ports:
     - "8787:8787"
    expose:
     - "8787"

#########################
## Shiny Service       ##
#########################
shiny:
    build: ./shiny/
    expose:
      - "3838"
    ports:
      - "3838:3838"
    volumes_from:
      - data
    volumes:
      - ./shiny/war/:/srv/shiny-server/war

#########################
## Web server Service  ##
#########################
nginx:
    build: ./nginx
    restart: always
    ports:
     - "8080:80"
     #- "8080:80"
    volumes_from:
     - shiny

#########################
## OAuth Service       ##
#########################
# Google OAuth Proxy
authproxy:
  build: ./oauth
  ports:
    - "80:4180"
  links:
    - nginx
  command: --cookie-secure=false --upstream="http://nginx:80" --http-address="0.0.0.0:4180" --redirect-url="http://idea.kippchicago.org/oauth2/callback" --email-domain="kippchicago.org"
  env_file:
    - ./oauth/.env
