#########################
## OAuth Service       ##
#########################
# Google OAuth Proxy
#authproxy:
#  build: ./oauth
#  command: --cookie-secure=false --upstream="http://nginx:80" --http-address="0.0.0.0:4180" --redirect-url="http://idea.kippchicago.org/oauth2/callback" --email-domain="kippchicago.org"
#  links:
#    - nginx
#  ports:
#    - "80:4180"
#  env_file:
#    - ./oauth/.env

version: '2.1'
services:
#########################
##  Cron / ETL Service ## using for Rstudio
#########################

  cron:
    build: ./cron/
    expose:
      - "8787"
    ports:
      - "8787:8787"
    #volumes:
      #- ./cron/jobs:/jobs
      #- /data
    volumes_from:
      - data
      - airflow
    #  - shiny



  #########################
  ##  Data Volume        ##
  #########################
  data:
      build: ./data/
      #volumes_from:
      #  - cron
      volumes:
       - /data
       - ./data/config:/config
      command: chmod -R 777 data

  ####################################
  ## Postrgres for Airflow service  ##
  ####################################
  postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
  #    - PGDATA=/var/lib/postgresql/data/pgdata
  #  volumes:
  #    - ./pgdata:/var/lib/postgresql/data/pgdata


  #########################
  ## Airflow service     ##
  #########################
  airflow:
    build: ./airflow
    depends_on:
      - postgres
      - data
      #- cron
    expose:
      - "8787"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/etc/airflow/dags
      - ./airflow/jobs:/jobs
    volumes_from:
      - data
      #- cron
      - shiny
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local

    #command: webserver


  #########################
  ## Shiny Service       ##
  #########################
  shiny:
    build: ./shiny/
    expose:
      - "3838"
    ports:
      - "3838:3838"
    volumes_from:
      - data
    volumes:
      - ./shiny/war/:/srv/shiny-server/war
      - ./shiny/map/:/srv/shiny-server/map
      - ./shiny/recruit/:/srv/shiny-server/recruit
      - ./shiny/assignments/:/srv/shiny-server/assignments
      - ./shiny/ktc/:/srv/shiny-server/ktc
