# global.R for session
message("Loading libraries for global environment")
library(shiny)
library(lubridate)
library(ggplot2)
#library(reshape)
#library(knitr)
library(RCurl)
library(xtable)
library(dplyr)
