---
title: "Student Recruitment"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: lumen
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(lubridate)
library(ggplot2)
library(dplyr)

load('/data/recruiting.Rda')

gauge_goals <-reg_goals_actual %>%
  filter(
    !is.na(cols)) %>%
  group_by(school, grade) %>%
  filter(date_eow == max(date_eow)) %>%
  group_by(school) %>%
  summarize(actual = sum(actual),
            goal = sum(overall_reg_goal),
            pct = round(100*actual/goal)) 

get_guage <- function(school_name){
  x <- gauge_goals %>%
    filter(school == school_name) 
  
  gauge(x$pct, 
        min = 0,
        max = 100, 
        symbol = '%',
        sectors = gaugeSectors(
          danger = c(0,75),
          warning = c(75,90),
          success = c(90,100)
        ))
}
```

```{r server, include=FALSE}


    output$plotRegs<-renderPlot({
      ggplot(reg_goals_actual, aes(x=date_eow, y=goal)) +
          geom_bar(stat="identity", fill = NA, color = "black") +
          geom_bar(aes(y=actual, fill=cols, color = cols), stat="identity") +
          geom_hline(aes(yintercept = overall_reg_goal)) +
          scale_fill_identity(guide="none") +
          scale_color_identity(guide="none") +
          facet_wrap(school ~ grade, scales = "free_y") +
          theme_bw() +
          labs(x = "Date",
               y = "Count")

      })



    output$reg_tbl <- renderText({
      if(is.null(input$reg_hover)) {

        #data_frame("Hover near bars for data" = NA)
      return(HTML("<b>Hover near bars for data</b>"))
      } else {

      reg_data  <- nearPoints(reg_goals_actual, input$reg_hover,threshold = 20, maxpoints = 1)


      html_text <- sprintf(
        "<b>School:</b> %s<br>
         <b>Grade:</b> %s<br>
         <b>Date:</b> %s<br>
         <b>Goal:</b> %s<br>
         <b>Actual:</b> %s<br>
         <b>Overall Goal:</b> %s<br>
         <b>Percent of current goal:</b> %s%%<br>
         <b>Percent of overall goal:</b> %s%%<br>
         <b>Forgone/gained budget:</b> %s
        ",
        reg_data$school,
        reg_data$grade,
        reg_data$date_eow,
        reg_data$goal,
        reg_data$actual,
        reg_data$overall_reg_goal,
        round(100*reg_data$pct_of_goal,1),
        round(100*reg_data$actual/reg_data$overall_reg_goal,1),
        scales::dollar(7000*(reg_data$actual - reg_data$overall_reg_goal))
        )

      HTML(html_text)
      }
    })

# eifs
    output$plotEIFs<-renderPlot({
      ggplot(eif_goals_actual, aes(x=date_eow, y=goal)) +
          geom_bar(stat="identity", fill = NA, color = "black") +
          geom_bar(aes(y=actual, fill=cols, color = cols), stat="identity") +
          geom_hline(aes(yintercept = overall_eif_goal)) +
          scale_fill_identity(guide="none") +
          scale_color_identity(guide="none") +
          facet_wrap(school ~ grade, scales = "free_y") +
          theme_bw() +
          labs(x = "Date",
               y = "Count")

      })

      output$eif_tbl <- renderText({
        if(is.null(input$eif_hover)) {

          #data_frame("Hover near bars for data" = NA)
        return(HTML("<b>Hover near bars for data</b>"))
        } else {

        eif_data  <- nearPoints(eif_goals_actual, input$eif_hover,threshold = 10, maxpoints = 1)


        html_text <- sprintf(
          "<b>School:</b> %s<br>
           <b>Grade:</b> %s<br>
           <b>Date:</b> %s<br>
           <b>Goal:</b> %s<br>
           <b>Actual:</b> %s<br>
           <b>Overall Goal:</b> %s<br>
           <b>Percent of current goal:</b> %s%%<br>
           <b>Percent of overall goal:</b> %s%%<br>
          ",
          eif_data$school,
          eif_data$grade,
          eif_data$date_eow,
          eif_data$goal,
          eif_data$actual,
          eif_data$overall_eif_goal,
          round(100*eif_data$pct_of_goal,1),
          round(100*eif_data$actual/eif_data$overall_eif_goal,1)
          )

        HTML(html_text)
        }
      })

```

Gauges show percent gained of overall registration goals by campus. Registration & EIF goals and progress shown in graphs below.

Row {data-height=160}
-----------------------------------------------------------------------

### One Primary

```{r}
renderGauge({get_guage("KOP")})
```

### One Academy

```{r}
renderGauge({get_guage("KOA")})
```

### Ascend Primary

```{r}
renderGauge({get_guage("KAP")})
```

### Ascend Middle

```{r}
renderGauge({get_guage("KAMS")})
```

### Create

```{r}
renderGauge({get_guage("KCCP")})
```

### Bloom

```{r}
renderGauge({get_guage("KBCP")})
```



Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Registrations
```{r regs}
fillRow(flex = c(3,4),
        plotOutput("plotRegs",
           hover="reg_hover",
           height = 600
           ),
        htmlOutput("reg_tbl")
)


```

### Enrollment Intent Forms

```{r}
fillRow(flex = c(3,4),
        plotOutput("plotEIFs",
           hover="eif_hover",
           height = 600
           ),
        htmlOutput("eif_tbl")
)

```

