---
title: "Grades Explorer"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---

```{r setup, include=FALSE}

library(dplyr)
library(lubridate)
library(ggplot2)
library(flexdashboard)
library(shiny)


# Load assignments data
load("/data/assignments.Rda")

# Source functions
source("lib/ass_helpers.R")

quarters <- c("Q1", "Q2", "Q3", "Q4")

courses <- sort(unique(assignments$course_number))
# Munges some data

```

PowerSchool Assignments
======================================================================
Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
selectInput("quarter", "Quarter", choices = quarters, selected = "Q4")

selectInput("course", "Course", choices = courses, selected = "kams8ela")

sliderInput("min_f", "Minimum F", 0, min = 0, max = 69, step=5)
```
**Select a student's assignments to see detail**
```{r}
div(tableOutput("detail"), style = "font-size:75%")


selectedRows <- reactive({brushedPoints(ass_adj(), input$plot_brush)})


output$detail <-renderTable({
      req(input$plot_brush)

      all_brush <- selectedRows()



      all_brush %>%
        filter(course_number == input$course) %>%
        ungroup() %>%
        mutate(cum_weighted_avg = round(cum_weighted_avg*100,1),
               Score = round(weighted_percent*100,1),
               Date = format(date, format = "%b %e")) %>%
        select(Date,
               Name = abbreviation, Score ,
               "Cum Avg"= cum_weighted_avg,
               "Cum Grade" = cum_grade) %>%
        arrange(Date)},

      # renderTable options
      include.rownames = FALSE,
      digits = 0

)
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Assignments Grades {.no-padding}

```{r}

plotOutput("bubbles",
            brush = brushOpts(id = "plot_brush", direction = "x"))

ass_adj <- reactive({

        assignments %>%
          ungroup() %>%
          filter(course_number == input$course) %>%
          adj_fs(input$min_f) %>%
          select(-starts_with("grade_cols")) %>%
          calc_cums


    })

p <- reactive({ass_plot(ass_adj(), quarter = input$quarter, course = input$course)})


output$bubbles <-renderPlot({p()$ass})



```

### Grades Histogram

```{r}

fillCol(height = 600, flex = c(NA,1),
        plotOutput("histo"),
        tableOutput("tab")
        )

output$histo <-renderPlot({p()$histo}, height = 200)

output$tab <- renderTable({
  ass_adj() %>%
    current_cum_grade %>%
    group_by(cum_grade) %>%
    summarize(N_grade = n()) %>%
    mutate(pct = round(N_grade/sum(N_grade)*100)) %>%
    select("Letter Grade" = cum_grade,
           "# of Students Earning" = N_grade,
           "% of Students Earning" = pct)},
  include.rownames = FALSE,
  alignment = c("lrr"),
  digits = 0)


```

```{r}


```
